version: '3.8'

services:
  # Apache Web Server with PHP
  web:
    build: ./web
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db
    restart: always

  # MySQL Database
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: always

  # FTP Server
  ftp:
    build: ./ftp
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      - USERS=ftpuser|ftppass
    volumes:
      - ./ftp/data:/home/ftpuser
    restart: always
