apiVersion: v1
kind: Service
metadata:
  name: ftp
spec:
  selector:
    app: ftp
  ports:
    - name: control
      port: 21
      targetPort: 21
    - name: pasv1
      port: 30000
      targetPort: 30000
    - name: pasv2
      port: 30001
      targetPort: 30001
  type: LoadBalancer

