apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftp
  template:
    metadata:
      labels:
        app: ftp
    spec:
      containers:
        - name: ftp
          image: delfer/alpine-ftp-server
          env:
            - name: USERS
              value: "test|test"
            - name: ADDRESS
              value: "0.0.0.0"
            - name: PASV_ADDRESS
              value: "192.168.49.2"  # e.g., 192.168.49.2 in Minikube
            - name: PASV_MIN_PORT
              value: "30000"
            - name: PASV_MAX_PORT
              value: "30009"
          ports:
            - containerPort: 21
            - containerPort: 30000
            - containerPort: 30009
          volumeMounts:
            - name: ftp-data
              mountPath: /home/test
      volumes:
        - name: ftp-data
          hostPath:
            path: /mnt/data/ftp
