apiVersion: v1
kind: Service
metadata:
  name: ftp
spec:
  selector:
    app: ftp
  type: LoadBalancer
  ports:
    - name: control
      port: 21
      targetPort: 21
      nodePort: 30021
    - name: pasv-min
      port: 30000
      targetPort: 30000
      nodePort: 30000
    - name: pasv-max
      port: 30009
      targetPort: 30009
      nodePort: 30009
